<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Profil extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Profil_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $profil = $this->Profil_model->get_all();

        $data = array(
            'profil_data' => $profil,
            'konten'=>"admin/profil/profil_list",
            'judul'=>"Profil Perusahaan",
        );
        $this->load->view('admin/container', $data);
    }
    
    public function update($id) 
    {
        $row = $this->Profil_model->get_by_id($id);

        if ($row) {
            $btsr = array(
                'assets/plugins/summernote/summernote-bs4.css',
            );
            $script = array(
                'assets/plugins/summernote/summernote-bs4.min.js',
                'assets/js/summer-note-area.js',
            );
            $data = array(
                'button' => 'Update',
                'action' => site_url('admin/profil/update_action'),
        		'profil_name' => set_value('profil_name', $row->profil_name),
        		'profil_values' => set_value('profil_values', $row->profil_values),
                'konten'=>"admin/profil/profil_form",
                'judul'=>"Update Profil Perusahaan",
                'bootstrap'=>$btsr,
                'script'=>$script,
	    );
            $this->load->view('admin/container', $data);
        } else {
            $this->session->set_flashdata('message', 'Maaf terjadi kesalahan');
            redirect("admin/Profil");
        }
    }
    
    public function update_action() 
    {
        $data = array(
          'profil_values' => $this->input->post('profil_values'),
        );
        $n = $this->input->post('profil_name');

        $this->Profil_model->update($n, $data);
        $this->session->set_flashdata('message', 'Berhasil Mengubah '.str_sentence($this->input->post('profil_name', TRUE)).'  Perusahaan' );
        redirect("admin/Profil");
    }

}

/* End of file Profil.php */
/* Location: ./application/controllers/Profil.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-14 15:21:28 */
/* http://harviacode.com */